### ISSUE TITLE
The rosplan_pytools.init() method cannot be found

### ISSUE THREAD

**Issue by V0idwu** [dgerod/rosplan_interface#19]
i've cloned the code from master branch and catkin_make successfully. The 'rosplan_pytools.init()' cannot execute correctly.

after running the scripts

```python
import rosplan_pytools

if __name__=="__main__":
  rospy.init_node("name")
  rosplan_pytools.init()
  rospy.spin()
```

a attribute error occurs

> 'module' object has no attribute 'init'
>  File "/home/voidwu/ros_ws/src/rosplan_demos/rosplan_demos_interfaces/rosplan_interface_movebase/scripts/test.py", line 18, in <module>
    rosplan_pytools.init()

So, should I use the lastest dev branch to solve this?

**Comment by dgerod** [comment]
No, you should use the master if you would like to work with current version of ROSPlan. 

The problem is that the README is not correct, you should do "import rosplan_pytools.rosplan" instead "import rosplan_pytools". Originally only "rosplan_pytools" exists but now there are two different packages "rosplan" and "rosparams", so you should initialize "rosplan" that is the one interaction with ROSPlan. 

Sorry for the inconvenience. I will fix it when I have time or you could create do it by creating a pull request.

**Comment by V0idwu** [comment]
> No, you should use the master if you would like to work with current version of ROSPlan.
> 
> The problem is that the README is not correct, you should do "import rosplan_pytools.rosplan" instead "import rosplan_pytools". Originally only "rosplan_pytools" exists but now there are two different packages "rosplan" and "rosparams", so you should initialize "rosplan" that is the one interaction with ROSPlan.
> 
> Sorry for the inconvenience. I will fix it when I have time or you could create do it by creating a pull request

Thanks a lot.
